Ivesti zuvu rikiavimo sekas
AplinkosMinisterija/biip-zuvinimas-api pull request #47
Opened 2024-01-10 10:40 UTC by DovMa

2024-01-18 09:45 UTC, ambrazasp requested changes

2024-01-18 09:45 UTC, ambrazasp commented on services/fishTypes.service.ts
> +    rest: 'PATCH /priority',
ar tikrai reik rest'o? cron'as ta padarys Tuo paciu gal geriau metodas, o ne action'as ir nereiks autorizacijos. viskas per cron bus. sakyciau testavimui action'as ok, bet i production gal nereiketu

2024-01-23 09:49 UTC, DovMa commented on services/fishTypes.service.ts
> +    update: {
replace neranet  sukuriamas.

2024-01-23 09:58 UTC, ambrazasp approved these changes

2024-01-23 10:02 UTC, merged