46 izuvinimo perziuros duomenu atnaujinimas
AplinkosMinisterija/biip-zuvinimas-api pull request #49
Opened 2024-01-17 15:33 UTC by DovMa

Kartu su amount ir reviewAmount validacija padarytos ir kitos fish stockingo validacijos.
Sita pull requesta reiketu pirmiau paziureti - https://github.com/AplinkosMinisterija/biip-zuvinimas-api/pull/47

2024-01-23 10:40 UTC, ambrazasp requested changes
Be kitu pastebejimu, dar reiketu ir prettier isijungti. Yra vietu kur pvz `24*60*60` ar dvigubu tarpu, praleistu tarpu ir pan. Prettier padarys `24 * 60 * 60` ir sutvarkys tarpus

2024-01-23 10:40 UTC, ambrazasp commented on services/fishBatches.service.ts
> +      await Promise.all(promises);
yra [`createMany`](https://github.com/moleculerjs/database/tree/master/docs#createmany-create-multiple-entities) action'as kuriuo galima tam naudotis. Priima masyva elementu - nereikes handlint visu promise'u

2024-01-23 10:40 UTC, ambrazasp commented on services/fishBatches.service.ts
> +        }
https://github.com/icebob/fastest-validator?tab=readme-ov-file#array

Array turi `items`. Tada jau ten yra objektas ir objektas turi properties. Yra pavyzdys pateiktam linke su array of objects validacijai

2024-01-23 10:40 UTC, ambrazasp commented on services/fishBatches.service.ts
> +        fishStocking: ctx.params.fishStocking || 1,
ar tikrai reiketu tokio fallback? Atrodo nelogiskas ypac kai pries tai delete'inama ir update'inama pagal fishstocking paramsa. Siulyciau pirma prasivaliduot pati fish stockinga su `resolve` ir `throwIfNotExist` bet tokio fallback nereiketu taikyt

2024-01-23 10:40 UTC, ambrazasp commented on services/fishBatches.service.ts
> +    await this.deleteExistingBatches(ctx, ctx.params.fishStocking, ctx.params.batches);
taip pat ir cia siulyciau prasivaliduot fishstocking su `resolve` ir `throwIfNotExist` flag'u - https://github.com/moleculerjs/database/tree/master/docs#resolve-get-entities-by-ids

2024-01-23 10:40 UTC, ambrazasp commented on services/fishBatches.service.ts
> +        fishStocking: ctx.params.fishStocking || 1,
fallback problema irgi

2024-01-23 10:40 UTC, ambrazasp commented on services/fishBatches.service.ts
> +    console.log('reviewBatches', ctx.params.batches);
console log'as

2024-01-23 10:40 UTC, ambrazasp commented on services/fishBatches.service.ts
>          fishStocking: ctx.params.fishStocking || 1,
fallback

2024-01-23 10:40 UTC, ambrazasp commented on services/fishBatches.service.ts
> +  async deleteExistingBatches(ctx: Context, fishStockingId: number, batches: any[]) {
`batches: FishBatch[]`

2024-01-23 10:40 UTC, ambrazasp commented on services/fishBatches.service.ts
> +      query: { fishStockingId },
`fishStockingId` nera tokio field'o yra `fishStocking` aprasytas service - https://github.com/AplinkosMinisterija/biip-zuvinimas-api/blob/bfc41aaaf17c0e2febcc06330b86db2287d75813/services/fishBatches.service.ts#L78-L86

2024-01-23 10:40 UTC, ambrazasp commented on services/fishBatches.service.ts
> +          return !batchToUpdate;
nereikalingas assign - uztektu return'o tiesiai. O kitas pastebejimas ar nevertetu cia tiesiog prasukt foreach ir iskart'o trinti / skipinti nei filtruoti, paskui mapinti o tada await'int

2024-01-23 10:40 UTC, ambrazasp commented on services/fishStockings.service.ts
> +    }
tokiam momentui galima daryti `ctx.call('tenants.resolve', {id: ctx.params.tenant, throwIfNotExist: true})` - uzteks vienos eilutes vietoje 4. Tas pats ir su stocking customer

2024-01-23 10:40 UTC, ambrazasp commented on services/fishStockings.service.ts
> +        if(!tenantUser) {
`find` grazina masyva - tai tenantUser `![]` -> `true` -> visada if'as bus false. Tada vertetu keisti i `findOne`.

2024-01-23 10:40 UTC, ambrazasp commented on services/fishStockings.service.ts
> +console.log('cancelFishStocking', fishStocking);
console log

2024-01-23 10:40 UTC, ambrazasp commented on services/fishStockings.service.ts
> +    }
`ctx.params.tenant = ctx.meta.profile` padarys ta pati - bus id arba undefined. Tai galima sutraukt iki 1 eilutes

2024-01-23 10:40 UTC, ambrazasp commented on utils/functions.ts
> +export const isCanceled = (fishStocking: any) => {
any

2024-01-23 10:40 UTC, ambrazasp commented on utils/functions.ts
> +export const isReviewed = (fishStocking: any, batches: FishBatch[]) => {
any

2024-01-23 18:11 UTC, DovMa commented on services/fishBatches.service.ts
> +    await this.deleteExistingBatches(ctx, ctx.params.fishStocking, ctx.params.batches);
sitas action neturi rest ir yra naudojamas tik vienoj vietoj fishStockingu servise. Ten yra ir taip batchu ir fishStockingo validacija, tai gautusi kad du kart tas pats daroma.

2024-01-23 18:20 UTC, DovMa commented on services/fishBatches.service.ts
> +        fishStocking: ctx.params.fishStocking || 1,
Jo cia nezinau ka tas fallback daro, panasu vienoj vietoj seniau buvo irasytas ir neatkreipus demesio visur pakopinau. O del throwIfNotExist tai validacija yra daroma fishStockingu servise. Tai manau nebutina cia irgi daryt, kadangi tik ten ir yra naudojami fishBatch'ai. Manau butu geriau apskritai parefactorinti visa sita logika, ir fishBatchus perkelti i fishStocking'u servisa kaip object[] fielda.

2024-01-25 09:21 UTC, ambrazasp approved these changes

2024-01-26 12:07 UTC, merged