57 galimybe filtruoti uetk statistika
AplinkosMinisterija/biip-zuvinimas-api pull request #58
Opened 2024-04-04 18:06 UTC by DovMa

2024-04-10 09:11 UTC, ambrazasp requested changes

2024-04-10 09:11 UTC, ambrazasp commented on services/fishStockings.service.ts
> +  }
sita dalyka galima igyvendint `@Event` t.y. `public` service pasidaryt `@Event` kurio name `fishStockings.updated` ar `created` ar `deleted` ir pan - ir tada daryt clean'a. Is kitos puses yra `fishStockings.*` - visu eventu klauso. As nesiulyciau cia to daryt - geriau event'ais o ne await'ais - jie trukdo response'u gavima

2024-04-10 09:11 UTC, ambrazasp commented on services/public.service.ts
> +      const condition = `fish_batches::jsonb @> '[{"fish_type": {"id": ${fishType} }}]'`;
sita dalis nepraeina per query. jei yra daugiau nei vienas masyvo elementas, tai pagal toki query praeina tik pirmas query.

Kitaip tariant - jei turim `[{fishType: 1},  {fishType:2}]` tai sitas query veiks tik tuo atveju jei bandoma bus `fishType:1` daryt. Jei `2` - gris tuscias atsakymas. Siulau pasibandyt.

2024-04-10 19:54 UTC, DovMa commented on services/public.service.ts
> +      const condition = `fish_batches::jsonb @> '[{"fish_type": {"id": ${fishType} }}]'`;
Tai kad praeina. Testavau ir pries tai ir dar karta pratestavau su keliais fish batchais.

2024-04-10 19:56 UTC, DovMa commented on services/public.service.ts
> +      const condition = `fish_batches::jsonb @> '[{"fish_type": {"id": ${fishType} }}]'`;
Ai ar turi omeny kad galima querinti pagal kelis fishType?

2024-04-11 06:09 UTC, ambrazasp approved these changes

2024-04-11 06:09 UTC, ambrazasp commented on services/public.service.ts
> +      const condition = `fish_batches::jsonb @> '[{"fish_type": {"id": ${fishType} }}]'`;
sorry, my bad situo klausimu. jei vienas fish type - viskas veikia gerai. buvau suklydes ir paziurejau i fishAge ir pagal ji nefiltravo. kitaip tariant ka maniau: jei `fishBatches: [...]` yra daugiau nei vienas objektas kuriame yra `fishType` keli ir skirtingais ID, tai toks query nepraeis ir isfiltruos tik pirma, o antro ne. Sumaisiau `fishType` su `fishAge` ko pasekoje patvirtinau hipoteze (klaidinga). 

Overall kai yra keli elementai su skirtingais `fishType` viskas gerai veikia. Cia mano susimalimas ir pasiklydimas tarp objektu ir field'u. Sorry

2024-04-11 06:13 UTC, merged